export const environment = {
  CATALOGUE_STORAGE_KEY: 'CATALOGUE_STORAGE_KEY',
  FAVOURITE_STORAGE_KEY: 'FAVOURITE_STORAGE_KEY',
  USER_STORAGE_KEY: 'USER_STORAGE_KEY',
  ACCESS_TOKEN_KEY: 'ACCESS_TOKEN_KEY',
  BOOK_REVIEWS: 'BOOK_REVIEWS',
};
