export const STORAGE_KEYS = {
  CATALOGUE: 'CATALOGUE_STORAGE_KEY',
  FAVOURITE: 'FAVOURITE_STORAGE_KEY',
  USER: 'USER_STORAGE_KEY',
  ACCESS_TOKEN: 'ACCESS_TOKEN_KEY',
  BOOK_REVIEWS: 'BOOK_REVIEWS'
} as const;
